name = "workers-mail"
main = "src/index.js"
compatibility_date = "2023-07-01"

workers_dev = false

[dev]
ip = "localhost"
port = 8787
local_protocol = "http"
host = "localhost:8787"

[route]
pattern = "api.server.diskost.site" ## API domain name
custom_domain = true

[vars]
BOUNCE_MAIL = false ## Whether to send bounce emails
CATCH_ALL_ADDRESS = 'server.diskost.site' ## Catch-all email address

EMAIL_DOMAINS = [ "diskost.site" ] ## Your email address domain name
DISABLE_REGISTRATION = true ## If true, disable new registration
DISABLE_SENDING = true ## If true, disable send functionality
SESSION_KV_NAME = "KV_EMAIL"
SESSION_TTL = 432000 ## Session expiration in seconds (Default: 5 days)

[[ kv_namespaces ]] ## Run 'npm run kv:create'
binding = "KV_EMAIL"
id = "4614e364fe278aeaa9fba76c71512b58"
preview_id = "36c28e6d36584ed89d8919a269828bcd"
