on:
  repository_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - run: npm install package.json
      - run: npx run build
      - run: wrangler login
      - run: npm run create
      - run: npm run init
      - run: npm run deploy
      - run: npm run deploy:front
