on:
  repository_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - run: npm install package.json
      - run: npm run front:build
      - run: wrangler login
      - run: npm run kv:create
      - run: npm run kv:init
      - run: npm run deploy
      - run: npm run deploy:front
